server:
  port: 9000
  url: "http://localhost:9000"
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: url-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/linkshrink_db
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
    import: optional:file:src/main/resources/.env[.properties]
  cache:
    type: caffeine
    cache-names: urlMappings
    caffeine:
      spec: maximumSize=500
      expireAfterWrite: 10m
      recordStats: true
      writer:
        expireAfterAccess:
          urlMappings: 1d
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
            auth: true
            starttls:
              enable: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      admin_user_email: ${MAIL_USERNAME}
      admin_password: $2a$10$i.7O7Ai2lIb28Ocz6pO1V.GwrxjD1uKXB.3r3VBABNdtc2CvHgjzG

jwt:
  secret: 324221acef13bc948c21f0ec1bca9e54d793ba5f5d08e103e5215030d432c163
  expiration-time: 3600000 # 1 hour
  refresh:
    expiration-time: 604800000 # 7 days