server:
  port: 8443
  url: "https://l-1.me"
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: url-service
  config:
    import: optional:file:src/main/resources/.env[.properties]
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  cache:
    type: caffeine
    cache-names: urlMappings
    caffeine:
      spec: maximumSize=1000
      expireAfterWrite: 30d
      recordStats: true

  mail:
    host: smtp.gmail.com
    username: ${ADMIN_EMAIL}
    password: ${MAIL_PASSWORD}
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      admin_user_email: ${ADMIN_EMAIL}
      admin_password: ${ADMIN_PASSWORD_PROD}

jwt:
  secret: ${JWT_SECRET_PROD}
  expiration-time: 3600000 # 1 hour
  refresh:
    expiration-time: 604800000 # 7 days