server:
  port: 9000
  url: "http://localhost:9000"
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: url-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/linkshrink_db
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
    import: optional:file:src/main/resources/.env[.properties]
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
            auth: true
            starttls:
              enable: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: 324221acef13bc948c21f0ec1bca9e54d793ba5f5d08e103e5215030d432c163
  expiration-time: 3600000