name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-test-frontend:
    name: Build and Test
    runs-on: ubuntu-22.04
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'

      - name: Install Dependencies
        run: npm install --prefix frontend

      - name: Build with Vite
        run: npm run build --prefix frontend

      - name: Test with Jest
        run: npm test --prefix frontend
